name: Build and Deploy Docker Image

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: self-hosted  # 로컬 Ubuntu의 actions 계정에서 실행됨

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build and tag Docker image
      run: |
        docker build --no-cache -t ${{ secrets.DOCKER_HUB_USERNAME }}/kws_fe:latest .
        docker tag ${{ secrets.DOCKER_HUB_USERNAME }}/kws_fe:latest ${{ secrets.DOCKER_HUB_USERNAME }}/kws_fe:latest

    - name: Deploy container locally
      run: |
        IMAGE=${{ secrets.DOCKER_HUB_USERNAME }}/kws_fe:latest
        docker stop KWS_FE || true
        docker rm KWS_FE || true
        docker run -d --name KWS_FE -p 25120:80 $IMAGE
        docker system prune -af
